import sys

def convert(in_file, out_file):
    with open(in_file, 'rb') as f:
        data = f.read()
    
    with open(out_file, 'w') as f:
        f.write('/* Auto-generated by tcl2c.py */\n')
        f.write('const char tcl_bootstrap[] = {\n')
        for i, b in enumerate(data):
            f.write(f"0x{b:02x}, ")
            if (i + 1) % 16 == 0:
                f.write('\n')
        f.write('0x00\n};\n')

if __name__ == '__main__':
    if len(sys.argv) != 3:
        print("Usage: python3 tcl2c.py <in.tcl> <out.h>")
        sys.exit(1)
    convert(sys.argv[1], sys.argv[2])
